### ISSUE TITLE
后端：Beta阶段功能的数据库设计

### ISSUE THREAD

**Issue by AmanogawaSaya** [SE2020-TopUnderstanding/BUAA-Campus-Tools-Backend#166]

**Comment by mushangui** [comment]
![image](https://user-images.githubusercontent.com/38529221/81712935-cd1e8480-94a7-11ea-8186-eab1e2de9d54.png)

**Comment by mushangui** [comment]
![image](https://user-images.githubusercontent.com/38529221/81713018-e9babc80-94a7-11ea-98f3-fe99661e4930.png)

**Comment by mushangui** [comment]
![image](https://user-images.githubusercontent.com/38529221/81713179-1ff83c00-94a8-11ea-87e5-3d0a66ef83f5.png)

**Comment by AmanogawaSaya** [comment]
![image](https://user-images.githubusercontent.com/41266480/81772834-718cdf00-9519-11ea-9b48-c89886cb60f8.png)
